### ISSUE TITLE
Loading count table for analysis in R

### ISSUE THREAD

**Issue by arvindsundaram** [BatzoglouLabSU/SIMLR#10]
I am trying to load cuffnorm genes.count_table in R to be analysed using SIMLR. I have tried vaires approached but I am unable to analyse the data. Could you help me in providing the script to load the data in R? I have attached the count file here. Thanks!
[genes.count_table.txt](https://github.com/BatzoglouLabSU/SIMLR/files/844747/genes.count_table.txt)

**Comment by danro9685** [comment]
Dear @arvindsundaram, 

I have created for you an RData with the loaded dataset (see attached). 

Best, 
Daniele Ramazzotti
[genes.count_table.RData.zip](https://github.com/BatzoglouLabSU/SIMLR/files/846253/genes.count_table.RData.zip)

**Comment by arvindsundaram** [comment]
Dear @danro9685,

Thanks for RData file. Unfortunately, it did not solve problem.
Error:
> res_example1 = SIMLR(X=genes.count_table, c=3)
Computing the multiple Kernels.
Performing network diffiusion.
Error in eigen(A, symmetric = TRUE) : infinite or missing values in 'x'
Called from: eigen(A, symmetric = TRUE)
Can you help me to resolve this? 

Regards, Arvind
