### ISSUE TITLE
Error in dyn.load

### ISSUE THREAD

**Issue by asmagen** [BatzoglouLabSU/SIMLR#11]
>       sourceCpp("/cbcbhomes/magen/scripts/clust/Rtsne.cpp")
Error in dyn.load("/tmp/RtmpqtrfEs/sourceCpp-x86_64-pc-linux-gnu-0.12.9/sourcecpp_8883692272e/sourceCpp_9.so") : 
  unable to load shared object '/tmp/RtmpqtrfEs/sourceCpp-x86_64-pc-linux-gnu-0.12.9/sourcecpp_8883692272e/sourceCpp_9.so':
  /tmp/RtmpqtrfEs/sourceCpp-x86_64-pc-linux-gnu-0.12.9/sourcecpp_8883692272e/sourceCpp_9.so: undefined symbol: _ZN4TSNE3runEPiS0_PdiS1_idbiS1_S1_b

**Comment by danro9685** [comment]
Dear @asmagen, 

I would suggest you to try to install SIMLR directly from R. Fist install the R library devtools and then once the library is installed you can install SIMLR with the following commands: 

library(devtools)
install_github("BatzoglouLabSU/SIMLR", ref = 'development')
library(SIMLR)

This should automatically do all the work for you. 

Best, 
Daniele

**Comment by asmagen** [comment]
Will it install all the large scale framework?

**Comment by danro9685** [comment]
Yes @asmagen it will also install the large scale.

**Comment by asmagen** [comment]
I still get an error:
>       library(SIMLR)
>       library(igraph)
>       clusters = SIMLR_Large_Scale(X=normalized$counts,c=environment$cluster.param2,k=30,kk=200)
Error in .Call("projsplx_R", c_input, c_output) : 
  C symbol name "projsplx_R" not in load table
