### ISSUE TITLE
C symbol name "projsplx_R" not in load table

### ISSUE THREAD

**Issue by asmagen** [BatzoglouLabSU/SIMLR#12]
Hello,
I installed the dev version of SIMLR and I get the following error when running:
  library(SIMLR)
  library(igraph)
  clusters = SIMLR_Large_Scale(X=normalized$counts,c=environment$cluster.param2,k=30,kk=200)
Error in .Call("projsplx_R", c_input, c_output) :
C symbol name "projsplx_R" not in load table

**Comment by danro9685** [comment]
Dear @asmagen , 

this is not happening to me, can you please provide some more information to replicate the error? 
Did you uninstall the version you had installed and re-installed SIMLR using the suggested commands form the development branch? 

Best, 
Daniel

**Comment by asmagen** [comment]
How should I uninstall?

**Comment by danro9685** [comment]
From R, remove.packages("SIMLR")

Close R and reopen and then to reinstall: 

library(devtools)
install_github("BatzoglouLabSU/SIMLR", ref = 'development')
library(SIMLR)

**Comment by asmagen** [comment]
No, it still gives the same error.

> session_info()
Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, linux-gnu           
 ui       X11                         
 language (EN)                        
 collate  C                           
 tz       America/New_York            
 date     2017-03-29                  

Packages -----------------------------------------------------------------------
 package       * version  date       source                               
 AnnotationDbi   1.36.2   2017-03-11 Bioconductor                         
 Biobase         2.34.0   2017-03-11 Bioconductor                         
 BiocGenerics    0.20.0   2017-03-11 Bioconductor                         
 BiocInstaller   1.24.0   2017-03-13 Bioconductor                         
 DBI             0.6      2017-03-09 CRAN (R 3.3.1)                       
 IRanges         2.8.1    2017-03-11 Bioconductor                         
 Matrix        * 1.2-8    2017-01-20 CRAN (R 3.3.1)                       
 R6              2.2.0    2016-10-05 CRAN (R 3.3.1)                       
 RCurl           1.95-4.8 2016-03-01 CRAN (R 3.3.1)                       
 RSQLite         1.1-2    2017-01-08 CRAN (R 3.3.1)                       
 RSpectra      * 0.12-0   2016-06-12 CRAN (R 3.3.1)                       
 Rcpp          * 0.12.10  2017-03-19 CRAN (R 3.3.1)                       
 RcppAnnoy     * 0.0.8    2016-10-01 CRAN (R 3.3.1)                       
 S4Vectors       0.12.1   2017-03-13 Bioconductor                         
 SIMLR         * 1.1.3    2017-03-29 Github (BatzoglouLabSU/SIMLR@887f452)
 XML             3.98-1.5 2016-11-10 CRAN (R 3.3.1)                       
 biomaRt       * 2.30.0   2017-03-11 Bioconductor                         
 bitops          1.0-6    2013-08-17 CRAN (R 3.3.1)                       
 codetools       0.2-15   2016-10-05 CRAN (R 3.3.1)                       
 curl            2.3      2016-11-24 CRAN (R 3.3.1)                       
 devtools      * 1.12.0   2016-06-24 CRAN (R 3.3.1)                       
 digest          0.6.12   2017-01-27 CRAN (R 3.3.1)                       
 git2r           0.18.0   2017-01-01 CRAN (R 3.3.1)                       
 httr            1.2.1    2016-07-03 CRAN (R 3.3.1)                       
 igraph        * 1.0.1    2015-06-26 CRAN (R 3.3.1)                       
 knitr           1.15.1   2016-11-22 CRAN (R 3.3.1)                       
 lattice         0.20-34  2016-09-06 CRAN (R 3.3.1)                       
 magrittr        1.5      2014-11-22 CRAN (R 3.3.1)                       
 memoise         1.0.0    2016-01-29 CRAN (R 3.3.1)                       
 pracma        * 1.9.9    2017-01-11 CRAN (R 3.3.1)                       
 quadprog        1.5-5    2013-04-17 CRAN (R 3.3.1)                       
 withr           1.0.2    2016-06-20 CRAN (R 3.3.1)

**Comment by danro9685** [comment]
This is really strange, it is working fine on my computer and on Bioconductor tests. @luca-dex do you have any idea of what may be happening? 

In any case please @asmagen give us some more info, such as what operative system you are using and R version. Also, did the package install correctly when you removed and reinstalled?

**Comment by asmagen** [comment]
It didn't produce any errors during the installation and I'm using a university unix server that runs well all the other packages.

**Comment by luca-dex** [comment]
> version R version 3.3.1 (2016-06-21)
Please @asmagen could you update your R versione to R stable ( 3.3.3 ) and try again?

**Comment by asmagen** [comment]
It works now. Thanks
But what are the k and kk params? And how should I choose them?

**Comment by danro9685** [comment]
Dear @asmagen , 

glad that it worked! 

About the parameters, you can use the defaults! 
If you want to play with the parameters, I would suggest you to carefully read the paper where the method and the software are presented: 

http://www.nature.com/nmeth/journal/vaop/ncurrent/full/nmeth.4207.html 
http://biorxiv.org/content/early/2017/03/21/118901 

Best, 
Daniele
