### ISSUE TITLE
Large Scale SIMLR Similarity Matrix

### ISSUE THREAD

**Issue by yanwu2014** [BatzoglouLabSU/SIMLR#13]
I noticed that the output S0 in the large scale implementation is not an n_cells x n_cells matrix. I was wondering what the interpretation of S0 was and also how to reconstruct an approximation of a n_cells x n_cells similarity matrix.

**Comment by danro9685** [comment]
Dear @yanwu2014 , 

for large scale you choose a number of component to use to approximate the n x n solution. This is a parameter that you can change. 

Obviously, the higher the better, with the trade-off with execution time. 

Best, 
Daniele

**Comment by Lakon** [comment]
Can you clarify what the S0 return value is? How does it describe the similarities (or approximate similarities)?
