### ISSUE TITLE
About the dataset in data folder

### ISSUE THREAD

**Issue by qianchenxi119** [BatzoglouLabSU/SIMLR#21]
To whom it may concern,

Hi, I am playing with SIMLR recently and wondering those sample data in data folder in Rdata format were log transformed or I have to do log10 transformation first to reproduce the result.
Any help will be highly appreciated!

Thanks!

**Comment by danro9685** [comment]
Dear @qianchenxi119 ,

the data should have already been transformed and they should be good as is to replicate the results. 
Please let us know if you have any issue in doing it. 

Best, 
Daniele
