### ISSUE TITLE
Error in network.diffusion function: eigen(A, symmetric = TRUE) : infinite or missing values in 'x'

### ISSUE THREAD

**Issue by steve2018** [BatzoglouLabSU/SIMLR#22]
Dear SIMLR team,

Thanks for developing this great algorithm! The clustering result is superior.

I found that one of my data sets gave me this error with the eigen function (see title), and I traced the problem to be in the network.diffusion step. I tried to remove the all-zero expression genes in my expression matrix and it didn't help. I wonder what have possibly gone wrong? More information can be provided upon request. Thank you very much!

Best,
Steve

**Comment by danro9685** [comment]
Dear @steve2018 ,

thanks for sharing this with us. Can you provide some data (also a toy example, not necessarily the ones you are using!) to reproduce the error? In this way we may be able to fix it. 

Thanks, 
Daniele

**Comment by steve2018** [comment]
Hi Daniele,

Thanks for your reply. I cut my data to contain 50 cells and it still gave
me the error. So I'll send that file to you. It's in TPM format, not
log-transformed. Thanks a lot!

Best,
Steve



On Fri, Jul 7, 2017 at 1:59 PM, Daniele Ramazzotti <notifications@github.com

**Comment by danro9685** [comment]
Thanks!

**Comment by steve2018** [comment]
Hi @danro9685 @wangboyunze ,

I actually figured out a way to fix the bug. It was very simple -- I just log-transformed TPM and it worked. Maybe I missed the part that the data should be in log(TPM+1) format. Otherwise I think you can remind the users that the data should be log-transformed. Thanks!

Best,
Steve

**Comment by danro9685** [comment]
@steve2018 thanks for the update!

**Comment by olhakholod** [comment]
@steve2018 thank you for your suggestion!

I had successfully run SIMLR on raw est_counts matrix for 384 scRNA samples, but I was unable to do that for 96 samples.
When I log transform data for 96 samples, SIMLR start working.

So, I am still curious why some datasets need log transformation, while others are not.
