### ISSUE TITLE
Error when running dyn.load("./R/projsplx_R.so")

### ISSUE THREAD

**Issue by tom-snir** [BatzoglouLabSU/SIMLR#25]
Couldn't find this issue reported before, I get the following error:

> dyn.load("./R/projsplx_R.so")
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
unable to load shared object 'C:/Users/SnirTom/Desktop/SIMLR/SIMLR-SIMLR/./R/projsplx_R.so':
LoadLibrary failure:  %1 is not a valid Win32 application.

the SIMLR package was installed via bioconductor, devtools is also loaded. Am i missing a dependency somewhere? I'm on windows 10 64 bit and the latest Rstudio.

**Comment by olhakholod** [comment]
I find thi in SIMLR/R_main_demo.R

NOTE 2: for Windows, the command dyn.load("./R/projsplx_R.so") needs to be substituted with the command dyn.load("./R/projsplx_R.dll"). 

This might be helpful.

**Comment by tom-snir** [comment]
Thank you for the suggestion @olhakholod , now I get a different error. Not sure if this is progress or not though:

> dyn.load("./R/projsplx_R.dll")
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
unable to load shared object 'C:/Users/SnirTom/Desktop/SIMLR/SIMLR-SIMLR/./R/projsplx_R.dll':
LoadLibrary failure:  The specified module could not be found.

**Comment by SamGG** [comment]
Hi,
May be should you look at https://github.com/BatzoglouLabSU/SIMLR/issues/8 especially the compilations at the end, although this should have been updated.

**Comment by tom-snir** [comment]
Apparently I was missing a few dependencies, mainly Cygwin. Also had some pathing issues for Rtools. 
Either way, after fixing/updating what I could, I am still getting errors. I think I'm giving up on SIMLR for now, the issue can be closed. Latest errors are:

C:\Users\SnirTom\Desktop\SIMLR\SIMLR-SIMLR\R>R CMD SHLIB -c projsplx_R.c
C:\Rtools\mingw_64\bin\nm.exe: projsplx_R.o: File format not recognized
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o projsplx_R.dll tmp.def projsplx_R.o -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.1/bin/x64 -lR
projsplx_R.o: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status

**Comment by followDm** [comment]
> ./R/projsplx_R.dll

i also read there, but i cant find "./R/projsplx_R.dll", i use R 4.4.1 on windows
