### ISSUE TITLE
Estimation of the number of cluster

### ISSUE THREAD

**Issue by charliex210** [BatzoglouLabSU/SIMLR#27]
Dear @danro9685 :
I really admire your work that might benefit scRNA-seq data research!

You have mentioned two heuristics, eigen-gap and separation cost, to estimate the desired clusters C in the paper, do you provide any implement of these methods in R or other language?

**Comment by danro9685** [comment]
Dear @charliex210 ,

we will had the heuristic in the next version of SIMLR. 

Best, 
Daniele
