### ISSUE TITLE
Error in if (cores < 1) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by bbimber** [BatzoglouLabSU/SIMLR#28]
Hello,

I am trying to run SIMLR through a docker VM.  I get this error:

Error in if (cores < 1) { : missing value where TRUE/FALSE needed

which is probably because detectCores() returns NA on this VM.  I do not know if there is a workaround for detectCores(); however, it would be nice if SIMLR had some kind of fallback/default value if detectCores() is NA.

Thanks.

**Comment by danro9685** [comment]
Thank you for your feedback, I will fix this asap.
