### ISSUE TITLE
cluster number estimation

### ISSUE THREAD

**Issue by chintanparekh2301** [BatzoglouLabSU/SIMLR#29]
HI,
Thank you for providing the cluster number estimation function. I couldn't find the function in the latest bioconductor version. 
1) Is there a version of simlr available for installation that has the cluster number estimation
 function ?

2) I copied the code from the 'bug fixing to num cluster estimation' link and am currently running it. My dataset has 3700 cells and 12000 genes. Roughly how long should it take to run (24 core 128 GB linux machine)? Running the SIMLR function on the same dataset with C=2 (using the regular SIMLR function and not the large scale dataset function) takes about 4 hours.

3) When running the SIMLR function for my dataset, given the size of the dataset,  I had to change the  K from the default value  of 10 to a value of 30 to get good clusters. Are there any parameters that I need to adjust when running the cluster number estimation function on my dataset?

Thank you very much

**Comment by danro9685** [comment]
Dear @chintanparekh2301 

The new release of SIMLR which will include the estimation of the number of clusters will be released in the next version of Bioconductor (in 1 months more or less). If you want to install directly the latest version from Github, those are the commands: 

library(devtools)  
install_github("BatzoglouLabSU/SIMLR", ref = "development")

Note that you need to install the R library devtools. 

Regarding questione 2, I can't give you a perfect estimate, but it should not take to much more than the regular 4 hours. 

For the parameters, I think those are ok. 

Best, 
Daniele
