### ISSUE TITLE
Turn SIMLR into a working R package

### ISSUE THREAD

**Issue by oneillkza** [BatzoglouLabSU/SIMLR#3]
Hi!

I've taken a stab at converting SIMLR into an actual R package, that can be installed via `R CMD INSTALL`, `install_github`, etc. See the https://github.com/oneillkza/SIMLR fork.

This did require deleting all of the Matlab source code, so I don't want to go creating a pull request right away. I would recommend that you separate the Matlab and R code into separate repositories, however!

**Comment by markrobinsonuzh** [comment]
I second this request to separate the MATLAB and R into separate repositories, so that a proper R package can be installed, without all the hoops to jump through.

I think the current hurdle of compiling the package as described is going to restrict uptake:
https://twitter.com/2plus2make5/status/841662380354359297

@oneillkza Is your compile-able package up to date with the code from the original repo?

Thanks, Mark

**Comment by danro9685** [comment]
Dear @markrobinsonuzh and @oneillkza, 

If you check all the branches, while the main SIMLR branch has both Matlab and R code, the branches master and development are valid R packages, and are already linked and hosted on Bioconductor: https://www.bioconductor.org/packages/release/bioc/html/SIMLR.html 

Best, 
Daniele

**Comment by oneillkza** [comment]
@danro9685 thanks, that's helpful! 

Also it just works with `install_github('BatzoglouLabSU/SIMLR')`, since `install_github` defaults to using the "master" branch, even though that isn't the default.

Could I suggest that you mention this in the README for the SIMLR branch, since that's still set to be the default? You could replace all of those complicated instructions for manually downloading dependencies and things with the command I mentioned above.

**Comment by markrobinsonuzh** [comment]
Great!  I second @oneillkza 's suggestion to modify the README .. installing direct from BioC (or github) is far easier than the manual way described.  Thanks, Mark

**Comment by danro9685** [comment]
Thank you for your suggestions! I have just updated the readme. Best, Daniele

**Comment by oneillkza** [comment]
Perfect! Thanks so much!
