### ISSUE TITLE
SIMLR_Estimate_Number_of_Clusters Error

### ISSUE THREAD

**Issue by qinzhu** [BatzoglouLabSU/SIMLR#30]
Hi,

I got this error when running SIMLR, could anyone help?

NUMC = 2:15
> simlr_ls = SIMLR_Estimate_Number_of_Clusters(as.matrix(exprs(gbm_log)),NUMC=NUMC,cores.ratio=1)
Error in base::which(x, arr.ind, useNames, ...) :
  argument to 'which' is not logical

**Comment by danro9685** [comment]
Dear @qinzhu , 

can you provide to me more information or a way to reproduce the error? 
This may be linked to the data give as input. 

Best, 
Daniele

**Comment by qinzhu** [comment]
Hi Daniele,
Thanks a lot for your reply. My data were 10x and pretty huge. I simply load it using the 10xCellRangerRkit and normalize and log transformed it before inputting to SIMLR. The error looks like there is a step inside the function calling "which", but the thing inside "which" was perhaps NULL? I'm wondering if you can check which step that might be and see what might go wrong. I'll try same command with some 10x public data and see if that's reproducible.

**Comment by danro9685** [comment]
Hi @qinzhu, 

it is very hard to me to understand what is going on without debugging. 
Why don't you try to select a small subset of your input like 20 of your 5000 cells a very small number of genes (like 50) and try again. If the error still occurs then pass me the data so that I can debug for your. 

Best, 
Daniele

**Comment by ccasar** [comment]
Hi,

I ran into the same issue as @qinzhu  with our 10X data, but I can reproduce that error with your test data as well. This minimal example works fine:
```
simlr_base <- '/opt/bioinf/SIMLR'
library(SIMLR)
library(Matrix)
library(parallel)
library(igraph)

source(file.path(simlr_base, "R/SIMLR_Estimate_Number_of_Clusters.R"))
source(file.path(simlr_base, "R/compute.multiple.kernel.R"))
source(file.path(simlr_base, "R/network.diffusion.R"))
load(file=file.path(simlr_base, "data/Test_1_mECS.RData"))

num_cl = 4:15
est_cl <- SIMLR_Estimate_Number_of_Clusters(Test_1_mECS$in_X, NUMC=num_cl, cores.ratio = 1)
```
But if you load the cellranger R package (what I assume is true for @qinzhu as well): 

```
source("http://cf.10xgenomics.com/supp/cell-exp/rkit-install-2.0.0.R")
library(cellrangerRkit)

est_cl <- SIMLR_Estimate_Number_of_Clusters(Test_1_mECS$in_X, NUMC=num_cl, cores.ratio = 1)

Error in base::which(x, arr.ind, useNames, ...) : 
  argument to 'which' is not logical
```

If I str() the matrix that is passed to `which` in debug mode, it is a `Formal class 'lgeMatrix' [package "Matrix"]`, but if you'd pass `matrix@x` to `which` it works as expected. Possibly there is some kind of namespace issue when load the cellranger R package?

**Comment by ccasar** [comment]
Just for future reference, since I ran into the same problem when the scater package was loaded, my solution for now is to unload all conflicting packges before running any SIMLR commands:

 ```
# "BiocGenerics" seems to be responsible for the problematic matrix redefinition, but is a
# dependency for many other packages that are automatically loaded, 
# so they have to be unloaded first
unloadNamespace("scater")
unloadNamespace("biomaRt")
unloadNamespace("AnnotationDbi")
unloadNamespace("Biobase")
unloadNamespace('IRanges')
unloadNamespace('S4Vectors')
unloadNamespace('BiocGenerics') 

est_cl <- SIMLR_Estimate_Number_of_Clusters(simlr_in, NUMC=num_cl, cores.ratio = 0.9)
```

**Comment by qinzhu** [comment]
@ccasar Thanks a lot for your comments. @danro9685 I'd suggest adding NAMESPACE:: before potential conflicting functions to avoid this issue since I believe more and more people are getting and analyzing 10x data today.

**Comment by danro9685** [comment]
Dear @ccasar and @qinzhu, 

thank you for your feedbacks, we will look into this. 
The next version of the tool is going to appear on Bioconductor in the next month. 

Thanks, 
Daniele
