### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by nick-webster** [BatzoglouLabSU/SIMLR#31]
Hi,  I was trying your SIMLR software and it worked fine on the BuettnerFlorian dataset you provided, although the clustering was not quite as depicted. The errors in the Iterations were different from those listed and then after the Iteration #1000 I received a error:

Warning message:
In SIMLR(X = BuettnerFlorian$in_X, c = BuettnerFlorian$n_clust,  :
  Maybe you should set a larger value of c.  

But the clustering did seem to work when I examined the 2D plot but the separations were not a s clean as the example given.
I would now like to use SIMLR to analyze some of our scSeq data.  I was looking at the format of the datasets examples you provide.  These are not simple matrices of the raw count data and contain much additional data.  It would be helpful if your examples started with the raw data matrix rather than  a pre-processed file.  What is the required format of the input data file?  Do I need to create a RData file similar to the examples or can I load an expression matrix into SIMLR?  A more detailed step-by-step manual would help.

Thanks, Nick

**Comment by danro9685** [comment]
Dear @nick-webster , 

first of all, the examples provided in the R Package (in the vignette) are reduced version of the original datasets, in fact, Bioconductor limits the size of the data which can be used in the examples. Because of this, they may give different results, in fact the data are not exactly the same as the ones in the papers. 

Concerning the inputs, you only need the expression matrix log transformed. Also you need to specify the number of clusters you want to search for. 

Please let me know if you have further inquiries. 

Best, 
Daniele

**Comment by nick-webster** [comment]
Hi Danielle,  thanks for the info.  I was not using logged data so will try that.

Nick
**********************************************************************
Nicholas Webster, Ph.D., M.A.
Professor of Medicine
Chief, Division of Endocrinology and Metabolism
Associate Director for Shared Resources, Moores Cancer Center
University of California, San Diego
9500 Gilman Drive
La Jolla CA 92093
(858) 534-6275








On Dec 5, 2017, at 1:58 PM, Daniele Ramazzotti <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear @nick-webster<https://github.com/nick-webster> ,

first of all, the examples provided in the R Package (in the vignette) are reduced version of the original datasets, in fact, Bioconductor limits the size of the data which can be used in the examples. Because of this, they may give different results, in fact the data are not exactly the same as the ones in the papers.

Concerning the inputs, you only need the expression matrix log transformed. Also you need to specify the number of clusters you want to search for.

Please let me know if you have further inquiries.

Best,
Daniele

**Comment by nick-webster** [comment]
Hi Danielle,  I used log2 data and loaded the table OK.  I used SIMLR_Estimate_Number_of_Clusters to estimate the clusters and got:

> SIMLR_Estimate_Number_of_Clusters(X = ryan, NUMC = 2:10, cores.ratio = 0)
$K1
[1] -31.776165  -2.147115  37.735200 -24.000854 -25.771739  25.496895  59.997182 -99.514676  99.991779

$K2
[1]  -47.664247   -2.862821   47.169000  -28.801024  -30.067028   29.139308   67.496829 -110.571863  109.990957

The help doc says the lowest number is the best estimate.  Does this mean the largest negative value? Or the lowest absolute value?

Thanks, Nick
**********************************************************************
Nicholas Webster, Ph.D., M.A.
Professor of Medicine
Chief, Division of Endocrinology and Metabolism
Associate Director for Shared Resources, Moores Cancer Center
University of California, San Diego
9500 Gilman Drive
La Jolla CA 92093
(858) 534-6275








On Dec 5, 2017, at 1:58 PM, Daniele Ramazzotti <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear @nick-webster<https://github.com/nick-webster> ,

first of all, the examples provided in the R Package (in the vignette) are reduced version of the original datasets, in fact, Bioconductor limits the size of the data which can be used in the examples. Because of this, they may give different results, in fact the data are not exactly the same as the ones in the papers.

Concerning the inputs, you only need the expression matrix log transformed. Also you need to specify the number of clusters you want to search for.

Please let me know if you have further inquiries.

Best,
Daniele

**Comment by danro9685** [comment]
Hi, 

the smaller, the better. E.g. -100 better than -10. 

Daniele

**Comment by nick-webster** [comment]
Hi Daniele,

I have run across another problem with importing data.  I aligned a different set of sc data with kallisto pseudo in batch mode.  The output is a matrix.tsv file that is a sparse matrix in COO format.  I tried running SIMLR on the sparse matrix but got an error that it was a non-conformable array.  The SIMLR documentation mentions using Matrix to import sparse matrices for SIMLR.  I have Matrix and futile.matrix installed. I can read the sparse matrix into R or python but haven’t figured out how to convert it to a dense matrix that SIMLR can use.  Is there an easy way to get SIMLR to recognize a sparse matrix file, or to convert it to a dense matrix.  I have been searching the web but haven’t come up with anything that works as yet.

Thanks, Nick
**********************************************************************
Nicholas Webster, Ph.D., M.A.
Professor of Medicine
Chief, Division of Endocrinology and Metabolism
Associate Director for Shared Resources, Moores Cancer Center
University of California, San Diego
9500 Gilman Drive
La Jolla CA 92093
(858) 534-6275








On Dec 5, 2017, at 4:55 PM, Daniele Ramazzotti <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

the smaller, the better. E.g. -100 better than -10.

Daniele
