### ISSUE TITLE
Error at t-sne step

### ISSUE THREAD

**Issue by goldenflaw** [BatzoglouLabSU/SIMLR#32]
I am getting the following error:

Could you help with this?

Thanks!

 k-nearest neighbour search.                                                                                                                                                          [104/1832]
Computing the multiple Kernels.
Performing the iterative procedure  5  times.
Iteration:  1 
Iteration:  2 
Iteration:  3 
Iteration:  4 
Iteration:  5 
Performing Kmeans.
Performing t-SNE.
*** Error in `/software/R-3.4.1-el7-x86_64/lib64/R/bin/exec/R': double free or corruption (!prev): 0x000000009538d6f0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7c619)[0x7f62028d2619]
/home/yangili1/local/R_libs/SIMLR/libs/SIMLR.so(_ZN4TSNE16symmetrizeMatrixEPPiS1_PPdi+0x38c)[0x7f61ef754e0c]
/home/yangili1/local/R_libs/SIMLR/libs/SIMLR.so(_ZN4TSNE3runEPiS0_PdiS1_idbiS1_S1_b+0x16b)[0x7f61ef75617b]
/home/yangili1/local/R_libs/SIMLR/libs/SIMLR.so(_Z9Rtsne_cppN4Rcpp6VectorILi14ENS_15PreserveStorageEEES2_S2_iddbiNS_6MatrixILi14ES1_EEb+0x538)[0x7f61ef74f288]
/home/yangili1/local/R_libs/SIMLR/libs/SIMLR.so(_SIMLR_Rtsne_cpp+0x28a)[0x7f61ef74921a]
/software/R-3.4.1-el7-x86_64/lib64/R/lib/libR.so(+0xdac6f)[0x7f6203126c6f]

**Comment by danro9685** [comment]
Dear @goldenflaw, 

thank you for letting us know. Could you provide some data to replicate this error? 
I am also including @luca-dex in the conversation. 

Best, 
Daniele

**Comment by danro9685** [comment]
Dear @goldenflaw, 

I could not reproduce this error. Is everything good in terms of your installation of the software? 
You may try to reinstall it and see if the error persists. 

In any case, if you could share the data to reproduce the error, we may look this further. 

Best, 
Daniele

**Comment by goldenflaw** [comment]
Thanks, I tried with a very big matrix (~10K cells by 20K genes), might that be the problem? It's a bit difficult to share the data with you immediately.

**Comment by danro9685** [comment]
Dear @goldenflaw, 

yes that may very well be the case, we tried our method on very large data, but there is the obvious limitation on the device you are running it. 

Best, 
Daniele

**Comment by februaryfang** [comment]
Dear Daniele，
Could you share your command lines ? I also tried SMILR on very large data(~8K cells by 27K genes), but my problem is the wrong value of cores.ratio.The program was ok when I used a small data set.

Best
februaryfang
