### ISSUE TITLE
multiprocessing

### ISSUE THREAD

**Issue by cimbusch** [BatzoglouLabSU/SIMLR#33]
Dear SIMLR team,

using SIMLR in single core mode seems to be fine, but when I switch to multicore things go wrong. Is this caused by R's socket limit of 128? How to fix that issue?

Thankful for any hint.

Cheers,
  Charles

library(SIMLR)

> example = SIMLR(X = BuettnerFlorian$in_X, c = 3, cores.ratio = 0)
Computing the multiple Kernels.
Performing network diffiusion.
Iteration:  1 
Iteration:  2 
Iteration:  3 
...
> example = SIMLR(X = BuettnerFlorian$in_X, c = 3, cores.ratio = 4)
Computing the multiple Kernels.
Error in socketConnection("localhost", port = port, server = TRUE, blocking = TRUE,  : 
  all connections are in use
Error in textConnection("rval", "w", local = TRUE) : 
  all connections are in use

**Comment by danro9685** [comment]
Dear @cimbusch, 

can you please provide more details about your error in order to reproduce it? 
I can run SIMLR in multi-core just fine on my laptop. 
Are you possibly running it on a server? If so, please check the configuration. 

Best, 
Daniele

**Comment by danro9685** [comment]
Just by a quick search on Google, check this: https://stackoverflow.com/questions/19248598/cant-open-sockets-for-parallel-cluster, for some reason R cannot open the sockets.
