### ISSUE TITLE
question about method description

### ISSUE THREAD

**Issue by februaryfang** [BatzoglouLabSU/SIMLR#34]
hello，
Thanks for your works.
I used the SIMLR package to analyze my scRNA-Seq data. It works very well.  I read the paper 'Visualization and analysis of single-cell RNA-seq data by kernel-based similarity learning' for getting more description information about method. Now, I have two questions.
1.  Is the truth of the main idea ‘multikernel learning’ here actually a combination of multiple methods(like PCA、Kmeans and t-SNE) ?
2.  You provide two intuitive methods to determine the number of desired clusters, Eigengap and Separation Cost. How can I understand the process that I get the final cluster number ?

best wish

**Comment by danro9685** [comment]
Dear @februaryfang, 

glad that you like our work. 

Not sure about the meaning of Q1: in SIMLR we combine multiple kernels to build a similarity matrix. 
Regarding Q2: you can find a detailed descriptions of the 2 heuristics in the supplementary materials provided in the paper. 

Please let me know if you need further clarifications. 

Best, 
Daniele

**Comment by februaryfang** [comment]
I run SMILR on very large data(8527 cells by 27K genes) successfully with SIMLR_Large_Scale function.
Now  I want to report the similarities computed by SIMLR(cell to cell). But my matrix S0  just has 8527 rows and 60 cols. Could you help to explain this result?

**Comment by danro9685** [comment]
Dear @februaryfang, 

the large scale implementation, first perform a reduction by PCA. That is way you end up with all your cells but less genes. 

Best, 
Daniele

**Comment by februaryfang** [comment]
Dear Daniele,
1.  I read the literature and documentation of SIMLR carefully. I am very confused about how to select modules based on the amount of data. From the point of view of the documentation, SIMLR is suitable for small-scale data, and SIMLR_Large_Scale is suitable for large-scale data. But if I use the SIMLR_Large_Scale module, I can't use SIMLR_Feature_Ranking module anymore. My data contains 8K cells and 27K genes. I tried to use SIMLR_Large_Scale to analyze. Although a lot of analysis time is saved, the similarity matrix of all cells cannot be obtained. And I cannot use the SIMLR_Large_Scale module further. Then I tried to use the SIMLR module to analyze the data. I got the results of the similarity matrix of all cells and gene prioritization , and it also took a long analysis time. How to select the analysis module based on the data?
2. I used the SIMLR and SIMLR_Feature_Ranking modules to analyze my data. I got the similarity matrix of all cells and gene prioritization. Then the similarity matrix of cell-to-cell in my result don't have an approximate block-diagonal structure with C blocks after visualization. And the p-value of top ranking gene is large， like 0.999999999.  Is my method wrong or is my data not good? How can I adjust parameters or filter data? 

Best wish

**Comment by danro9685** [comment]
Dear @februaryfang, 

the standard implementation of SIMLR is the one leading the better results, so if you can use it, that is the best option. 

SIMLR large scale is provided for when standard SIMLR cannot be run for computational problems. But if you can run it, please use the standard version. 

Best, 
Daniele
