### ISSUE TITLE
sourceCpp error

### ISSUE THREAD

**Issue by cramirezs** [BatzoglouLabSU/SIMLR#35]
Dear developers,

I have been trying to use the large scale code you provided with my 30k cells, but there is one step that I cannot workout what the problem is. When I run `sourceCpp(file = paste0( git.path,"src/Rtsne.cpp"))` I get the following error:

make: Warning: File `Rtsne.cpp' has modification time 149 s in the future
git.path/src/tsne.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
make: *** [sourceCpp_8.so] Error 1
g++  -I/share/apps/R/3.4/lib64/R/include -DNDEBUG   -I"/home/ciro/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"git.path/src" -I/usr/local/include   -fpic  -g -O2  -c Rtsne.cpp -o Rtsne.o
g++ -shared -L/share/apps/R/3.4/lib64/R/lib -L/usr/local/lib64 -o sourceCpp_8.so git.path/src/tsne.o git.path/src/sptree.o Rtsne.o -L/share/apps/R/3.4/lib64/R/lib -lR
Error in sourceCpp(file = paste0(git.path, "src/Rtsne.cpp")) :
  Error 1 occurred building shared library.

Do you have an idea of what it could possibly be?

**This is my session**
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /mnt/BioApps/R/3.4/lib64/R/lib/libRblas.so
LAPACK: /mnt/BioApps/R/3.4/lib64/R/lib/libRlapack.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.13.5    RColorBrewer_1.1-2 SIMLR_1.5.1        igraph_1.2.1      
[5] RSpectra_0.12-0    RcppAnnoy_0.0.10   pracma_2.1.4       Matrix_1.2-12     
[9] Rcpp_0.12.16      

loaded via a namespace (and not attached):
 [1] lattice_0.20-35  codetools_0.2-15 withr_2.1.2      digest_0.6.15   
 [5] grid_3.4.0       magrittr_1.5     tools_3.4.0      parallel_3.4.0  
 [9] compiler_3.4.0   pkgconfig_2.0.1  memoise_1.1.0

**Comment by danro9685** [comment]
Dear @cramirezs , 

I suggest you try to first remove all .o and .so files in the directory before compiling them, as previous versions may conflict. 

In any case, an easier way to install and use the R package would be by installing it with intall_github or from Bioconductor as explained in the readme. 

Best, 
Daniele
