### ISSUE TITLE
SIMLR_Large_Scale error "double free or corruption"

### ISSUE THREAD

**Issue by z5ouyang** [BatzoglouLabSU/SIMLR#37]
Running this for 30k single cells. And the error "double free or corruption (!prev)" is shown on my ubuntu 16.04, 16G memory desktop, as well as CentOS7, 700G memory clusters.

Performing t-SNE.
*** Error in `/usr/lib/R/bin/exec/R': double free or corruption (!prev): 0x0000000049cc41d0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f58b84777e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f58b848037a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f58b848453c]
/home/.../R/x86_64-pc-linux-gnu-library/3.4/SIMLR/libs/SIMLR.so(_ZN4TSNE16symmetrizeMatrixEPPiS1_PPdi+0x39d)[0x7f58a18cc44d]
/home/.../R/x86_64-pc-linux-gnu-library/3.4/SIMLR/libs/SIMLR.so(_ZN4TSNE3runEPiS0_PdiS1_idbiS1_S1_b+0x170)[0x7f58a18cd6c0]
/home/.../R/x86_64-pc-linux-gnu-library/3.4/SIMLR/libs/SIMLR.so(_Z9Rtsne_cppN4Rcpp6VectorILi14ENS_15PreserveStorageEEES2_S2_iddbiNS_6MatrixILi14ES1_EEb+0x39b)[0x7f58a18c6a8b]
/home/.../R/x86_64-pc-linux-gnu-library/3.4/SIMLR/libs/SIMLR.so(_SIMLR_Rtsne_cpp+0x299)[0x7f58a18c0e99]

Thank you!

**Comment by danro9685** [comment]
Dear @z5ouyang, 

are you using the R implementation of SIMLR Large Scale? Did you install it from Bioconductor? http://bioconductor.org/packages/release/bioc/html/SIMLR.html 

Best, 
Daniele

**Comment by z5ouyang** [comment]
Thanks for the reply. Again, cell number is 30k, not sure if that's the issue.
Yes, I installed through bioconductor which endup with a version something like 1.3...
Then I noticed that v 1.6 is available on bioconductor, I downloaded and installed the v1.6 and the same errors.

R version 3.4.3

**Comment by danro9685** [comment]
Dear @z5ouyang, 

it is very likely that this is related with the size of 30k cells. But I will look more carefully into it. 
In the mean time, would it be possible for you to try out the Matlab implementation? 

Best, 
Daniele

**Comment by z5ouyang** [comment]
Sorry, I don't have Matlab.
But I figured out, the input matrix format might not be correct originally, since I used seurat object"@scale.data". Now it is working, after make the right matrix.
Thank you!

**Comment by danro9685** [comment]
Great!
