### ISSUE TITLE
Example code calls a "compare" function not present in the package

### ISSUE THREAD

**Issue by oneillkza** [BatzoglouLabSU/SIMLR#4]
The example code in main_examples.R seems to call a function called `compare`, which isn't present anywhere within the package. It also does not seem to be the `compare` function from the CRAN `compare` package, either.

Is this maybe a missing dependency or some code that never got checked in?

**Comment by luca-dex** [comment]
The `compare` is defined in `igraph` which is not a dependency (at the moment).
Try `library(igraph)` to solve the problem.
