### ISSUE TITLE
Exection error

### ISSUE THREAD

**Issue by jefferyUstc** [BatzoglouLabSU/SIMLR#43]
when using SIMLR，I found a error below(In centos 7):
`res_example = SIMLR_Estimate_Number_of_Clusters(df, NUMC = NUMC)`
Error in socketConnection("localhost", port = port, server = TRUE, blocking = TRUE,  : 
  all connections are in use

how can i fix this?

**Comment by danro9685** [comment]
Dear @jefferyUstc, 

thanks for your interest in SIMLR. 

The error your are having seems to be related to the parallelization of SIMLR execution (using parallel R package). I am not sure about the cause, are you running this on a server where the process does not have required credential to run new processes? 

In any case, to get more information on the error, you can try to write to files a log when executing parallel processes. You can do this as follow: 

`library(parallel)`
`cl <- makeCluster(2,outfile="log.txt")`
`stopCluster(cl)`

If this code gives you error, as in SIMLR, than you can use the information in log.txt to solve the problem. 

Hope this helps, 
Daniele
