### ISSUE TITLE
Error in inDL(x, as.logical(local), as.logical(now), ...) :    unable to load shared object 'D:/singlecell/projsplx_R.dll':   LoadLibrary failure:  %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by xuebaliang** [BatzoglouLabSU/SIMLR#44]
Hello,  I meet some trouble when I run your code. My compute is Windows64.
 NOTE 2: for Windows, the command dyn.load("./R/projsplx_R.so") needs to be 
# substituted with the command dyn.load("./R/projsplx_R.dll").
I can't find the file "projsplx_R.dll". So can you upload it to github?

**Comment by danro9685** [comment]
Dear @xuebaliang, 

thank you for your interest in SIMLR! 

You need to generate this dll yourself (depending on the specs of your computer) as explained in the readme. However, if you install the tool directly from Bioconductor (https://www.bioconductor.org/packages/release/bioc/html/SIMLR.html) the whole process will be automatic. 

Thanks, 
Daniele
