### ISSUE TITLE
memory errorError in if (row_normalize[i, j] != 0) { :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by xuebaliang** [BatzoglouLabSU/SIMLR#46]
I just change a machine to do experiment and settle the memory problem. But next I meet another problem, how can I avoid it? 
[1] "begin SIMLR cluster"
Performing fast PCA.
Performing k-nearest neighbour search.
Computing the multiple Kernels.
Performing the iterative procedure  5  times.
Iteration:  1 
Iteration:  2 
Iteration:  3 
Iteration:  4 
Iteration:  5 
Performing Kmeans.
Performing t-SNE.
The main loop will be now performed with a maximum of 300 iterations.
Performing iteration 1.
‘’‘
Performing iteration 300.
Error in if (row_normalize[i, j] != 0) { : 
  missing value where TRUE/FALSE needed

**Comment by danro9685** [comment]
Dear @xuebaliang, 

this one is more tricky and I would need to reproduce it in order to tell you what is happening. 
However, it seems you are using the R version of SIMLR, I would suggest you to try the MATLAB one that may solve the issue. 

Best, 
Daniele
