### ISSUE TITLE
R meet fetal error when use SILMLR package

### ISSUE THREAD

**Issue by wwn7268** [BatzoglouLabSU/SIMLR#47]
Hi SIMLR team,

I am a student from China. I am using your R packages "SIMLR" to analysis single-cell RNA-seq data.  I need to use the function "SIMLR_Large_Scale" to cluster big dataset. For some datasets, it runs normally. However, for others it may meet fetal error when running t-sne and terminate R. I want to know what happened and how to solve it.  Thank you very much!

Best regard,
Tommy

**Comment by wwn7268** [comment]
Hi SIMLR team,

I am a student from China. I am using your R packages "SIMLR" to analysis single-cell RNA-seq data. I need to use the function "SIMLR_Large_Scale" to cluster big dataset. For some datasets, it runs normally. However, for others it may meet fetal error when running t-sne and terminate R. I want to know what happened and how to solve it. Thank you very much!

Best regard,
Tommy

**Comment by danro9685** [comment]
Dear @wwn7268, 

I believe this may be a memory issue due to very big datasets or reduced memory where you are running SIMLR. 

But to give you more feedbacks, I would need to know something more about when it gives you fatal error. 

Best, 
Daniele

**Comment by wwn7268** [comment]
For example,when I running a dataset with 23000 genes and 1000 cells using "SIMLR_Large_Scale". It can run it correctly before t-SNE, but terminate after it star the step "performing t-SNE".

**Comment by danro9685** [comment]
Dear @wwn7268, 

I will need to be able to reproduce this in order to help you. Are you using the R package? One think you may try is to use MATLAB implementation. 

Best, 
Daniele

**Comment by yulijia** [comment]
I meet the same problem even using the latest package 1.18.0
@danro9685  would you mind providing a parameter officially in the R package to get rid of the TSNE step?

```r
if (calculate_TSNE==FALSE){
do not calculate TSNE, don't return ydata
}else{
calculate TSNE, and return ydata
}
```
