### ISSUE TITLE
how to add noises or dropout to data?

### ISSUE THREAD

**Issue by xuebaliang** [BatzoglouLabSU/SIMLR#48]
Hi, I have some question about the robustness experiments. How do you complement the noises or dropout experiments? Need it to generate random numbers in [0,1] to compare with the dropout rate pre-specified to mask the data? Can you give me some related code? Thanks!

**Comment by danro9685** [comment]
@wangboyunze, @junjiezhujason do you want to answer to this question? 

Best, 
Daniele
