### ISSUE TITLE
the row sum of the similarity(estimated by the SIMLR) isn't one!

### ISSUE THREAD

**Issue by yuxiaokang-source** [BatzoglouLabSU/SIMLR#55]
```
clear
load("./data/Test_1_mECS.mat")
rng default % for reproducibility
C = max(true_labs); %%% number of clusters
rng(1,'twister'); %%% for reproducibility
[y, S, F, ydata,alpha] = SIMLR(in_X,C,10);
NMI_i = Cal_NMI(y,true_labs);
fprintf(['The NMI value for dataset mECS is %f\n'], NMI_i);
sum(S,2)
```
```
ans =

    0.3367
    0.3377
    0.3021
    0.3277
    0.2230
    0.7691
    0.3980
    0.3531
    0.8002
    0.7585
    0.7592
    0.4676
    0.3173
    0.2731
    0.2184
    0.2010
    0.3007
```
what should I do if I want to get a normalized simaility matrix(the row sum of the matrix is 1)?

**Comment by danro9685** [comment]
Hi @yuxiaokang-source, 

SIMLT does not normalize the output similarity (S). 
If you need a normalized S, you need to do it yourself after the inference. 

Best, 
Daniele

**Comment by yuxiaokang-source** [comment]
thank you for you reply。In my view, the diag of a simililarity matrix is arbitrary. In the optimization problem mentioned in the paper，the row sum of similarity is equal to 1, what is meaning of this constraint? Could you give a  
intuitive interpretation of this constraint? If I din't apply this restriction on S, it will change the result  very differently? I don't think is the specification of the result S. Because the row sum of S can have an influence on the norm of matrix.
