### ISSUE TITLE
confusion about the implementation of Network_Diffusion

### ISSUE THREAD

**Issue by yuxiaokang-source** [BatzoglouLabSU/SIMLR#57]
Thanks for developing this great algorithm! I am very interested in the algorithm. So I have read the source code of implementation(Matlab version) in detail. But I have no idea about some details in the code, for example, in the function ```Network_DIffusion(A,K) ,d = (1-alpha)*d./(1-alpha*d.^beta);``` I don’t know why I have to transform the eigenvalue of matrix P, It looks very strange. Why I substitute the ```D``` by```d``` (the eigenvalue of  matrix P) for getting ``` W```, Can you given me some intuitive interpretation?
```
function W = Network_Diffusion(A, K)
%K = min(2*K, round(length(A)/10));
A = A-diag(diag(A));
P = (dominateset(double(abs(A)),min(K,length(A)-1))).*sign(A);
DD = sum(abs(P'));
P = P + (eye(length(P))+diag(sum(abs(P'))));
P = (TransitionFields(P));
[U,D] = eig(P);
d = real((diag(D))+eps);
alpha = 0.8;
beta = 2;
d = (1-alpha)*d./(1-alpha*d.^beta);


D = diag(real(d));
W = U*D*U';

W = (W.*(1-eye(length(W))))./repmat(1-diag(W),1,length(W));
D=sparse(1:length(DD),1:length(DD),DD);
W=D*(W);
W = (W+W')/2;

end
```

**Comment by danro9685** [comment]
Bo (@wangboyunze) it the best person to give an answer to this questions.
