### ISSUE TITLE
Issue about compiling matlab code

### ISSUE THREAD

**Issue by QianpengLi577** [BatzoglouLabSU/SIMLR#59]
Thanks for developing this great algorithm. When I run SETUP.m to compile code，it occurs the following errors：

错误使用 mex
g++: error: \-fexceptions: No such file or directory

出错 SETUP (line 15)
mex CXXFLAGS="\$CXXFLAGS -std=c++11 -lm -lgsl -lgslcblas -O3 -ffast-math" mex_KNN_Annoy.cpp -largeArrayDims -I../External/

When I use the code `mex mex_KNN_Annoy.cpp -largeArrayDims -I../External/`

The error is 

In file included from E:\deepimpute\SC for sister\test_SIMLR\MATLAB\src\mex_KNN_Annoy.cpp:12:
..\External/annoylib.h:30:10: fatal error: mman.h: No such file or directory
 #include "mman.h"
          ^~~~~~~~
compilation terminated

My OS is Windows, should I compile it in Linux?

**Comment by danro9685** [comment]
Dar @QianpengLi577, 

Thanks for your interest in our tool! 
Your issue would seem a compiler configuration problem. By quickly searching it, it would seem that <mman.h> is a Unix header not available on Windows. 
Please try to run it on Linux and let us know if this works. 

Thanks, 
Daniele

**Comment by QianpengLi577** [comment]
Dear @danro9685 

Thanks for your reply!
Because it's a little difficult for me to use Linux here, I finally chose the R version, and it works well.

Best Regards,
Qianpeng Li

**Comment by danro9685** [comment]
Great, closing this.
