### ISSUE TITLE
cannot calculate tsne

### ISSUE THREAD

**Issue by shizhuomu** [BatzoglouLabSU/SIMLR#63]
Hi,

I'm trying to apply SIMLR_Large_scale with 24762 cells * 33592 genes. However, everytime it runs to "Performing t-SNE.", the Rstudio will shutdown. I thought it might be because the matrix is too large. Then I ran the source code line by line and it turned out that my server can definitely handle these several hundreds Mb matrix with 300G memory. When it came to 190 line in SIMLR_Large_Scale.R, it said "no function called Rtsne_cpp". So I tried to implement Rtsne.cpp into R with sourceCpp() function and it said :

```
> /gpfs/fs001/cbica/home/mushi/projects/scRNAproject/SIMLR_source/SIMLR-SIMLR/src/tsne.o: file not recognized: File format not recognized
> collect2: error: ld returned 1 exit status
> make: *** [sourceCpp_4.so] Error 1
> g++ -std=gnu++14 -I"/cbica/software/external/R-project/4.2.2/lib64/R/include" -DNDEBUG   -I"/gpfs/fs001/cbica/home/mushi/R/x86_64-pc-linux-gnu-library/4.2/Rcpp/include" -I"/gpfs/fs001/cbica/home/mushi/projects/scRNAproject/SIMLR_source/SIMLR-SIMLR/src" -I/usr/local/include   -fpic  -g -O2  -c Rtsne.cpp -o Rtsne.o
> g++ -std=gnu++14 -shared -L/cbica/software/external/R-project/4.2.2/lib64/R/lib -L/usr/local/lib64 -o sourceCpp_4.so /gpfs/fs001/cbica/home/mushi/projects/scRNAproject/SIMLR_source/SIMLR-SIMLR/src/tsne.o /gpfs/fs001/cbica/home/mushi/projects/scRNAproject/SIMLR_source/SIMLR-SIMLR/src/sptree.o Rtsne.o -L/cbica/software/external/R-project/4.2.2/lib64/R/lib -lR
> Error in sourceCpp("/gpfs/fs001/cbica/home/mushi/projects/scRNAproject/SIMLR_source/SIMLR-SIMLR/src/Rtsne.cpp") : 
>   Error 1 occurred building shared library.
```

Does anyone have any idea what can I do next or how to fix this issue?

**Comment by danro9685** [comment]
Dear @shizhuomu,

How did you install SIMLR and which version of R do you use?
Please refer to the latest implementation available from Bioconductor.
The setup should be automatic (no need to run sourceCpp).

All the best,
Daniele
