### ISSUE TITLE
Undefined function or variable 'projsplx_c'.

### ISSUE THREAD

**Issue by hajerkr** [BatzoglouLabSU/SIMLR#65]
Hello,

1.  I am trying to run the demo file for the small datasets, however I get the error: `Undefined function or variable 'projsplx_c'.`
Is that due to not running SETUP.m ? I thought that was needed for large scale dataset demo / runs only. Please let me know! Even when I tried running the setup, I get 

```
Error using mex
g++: error: \-fexceptions: No such file or directory
```
But I'd like to know if this step is necessary before investing time in it.

2. Also, I am not entirely clear on the input format needed to do the clustering. I have my nxm matrix, do I need the true labels as input as well? FYI, I am using SIMLR the way [this paper ](https://www.frontiersin.org/articles/10.3389/fninf.2018.00070/full#B61)put it in use.

3. Last but not least, how big is a big dataset? I would have approximately 400 subjects, with 900K features each. Any inisight would be great, thanks

**Comment by danro9685** [comment]
Dear @hajerkr,

Thanks for your interest in SIMLR!
Yes, you need to compile the file projsplx_c by MATLAB, as SIMLR uses this C function.

As inputs, please consider the one in the data directory of the repository.

All the best,
Daniele
