### ISSUE TITLE
Identify cluster memberships

### ISSUE THREAD

**Issue by hajerkr** [BatzoglouLabSU/SIMLR#66]
Hello!

Is there a way to extract information about which samples belong to which clutsters? And in the event where I have results as pictured below, do you suggest I increase the number of estimated clusters? I am basically trying to figure out why these sub-groups come up, and if there are intrinsic differences between the samples that is worth investigating. Thanks!

<img width="304" alt="verona+filtcontrols" src="https://github.com/BatzoglouLabSU/SIMLR/assets/13291010/17e78965-fd98-41ad-8e5e-a6b3861ac936">

**Comment by danro9685** [comment]
Dear @hajerkr,
You have the assignments as a numeric vector where samples are ordered a the inputs, so you can match them directly.
And sure, you can consider different number of clusters for exploration.
All the best,
Daniele

**Comment by hajerkr** [comment]
Thanks for the quick response @danro9685 , sorry can you clarify though? Are you referring to the assignments in this line?

 [y, S, F, ydata,alpha] = SIMLR(data,C,10,figure_titles{i});

**Comment by danro9685** [comment]
Yes, you should have the clusters in the y variable. and the position for each sample should match your inputs.
