### ISSUE TITLE
invalid ELF header in projsplx_R.so when trying to load with dyn.load

### ISSUE THREAD

**Issue by yanwu2014** [BatzoglouLabSU/SIMLR#9]
Hey guys, 

I was trying to test out the SIMLR_Large_Scale function but I'm having trouble loading the shared object. I'm getting the same error across two different linux servers, running R 3.3.2. The full error message is:

```
Error in dyn.load("~/SIMLR/R/projsplx_R.so") :
  unable to load shared object '/media/Home_Raid1/yan/SIMLR/R/projsplx_R.so':
  /media/Home_Raid1/yan/SIMLR/R/projsplx_R.so: invalid ELF header

```
Any ideas?

Thanks!
Yan

**Comment by SamGG** [comment]
Hi,
I made it run on Windows, so Linux should not be a big deal ;-) More seriously, did you compile the C code as stated in the 2) of the R installation section of the README? The given so library is stated to correspond to MacOS.

**Comment by yanwu2014** [comment]
Ah thanks I need to read the instructions more carefully. I was just looking at the example R script. It works fine now.
